# Generated by Django 4.1.7 on 2023-06-24 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
